executable    = /afs/cern.ch/user/o/ocerri/work/CMSSW_10_2_3/src/ntuplizer/BPH_RDntuplizer/jobSubmission/CMSSWCondorJob.sh
arguments      = /afs/cern.ch/user/o/ocerri/work/CMSSW_10_2_3/src/ntuplizer/BPH_RDntuplizer config/cmssw_privateMC_Tag_B0_MuDmst-pD0bar-kp.py /afs/cern.ch/user/o/ocerri/cernbox/BPhysics/data/cmsMC_private/BPH_NoCuts_Tag-B0_MuNuDmst-pD0bar-kp_13TeV-pythia8_SoftQCD_PTFilter5_0p0-evtgen_HQET2_central_PU35_10-2-3_v0/B02DstMu_candidates/cfg/file_list_$(ProcId).txt /afs/cern.ch/user/o/ocerri/cernbox/BPhysics/data/cmsMC_private/BPH_NoCuts_Tag-B0_MuNuDmst-pD0bar-kp_13TeV-pythia8_SoftQCD_PTFilter5_0p0-evtgen_HQET2_central_PU35_10-2-3_v0/B02DstMu_candidates/out_$(ProcId).root
output         = /afs/cern.ch/user/o/ocerri/cernbox/BPhysics/data/cmsMC_private/BPH_NoCuts_Tag-B0_MuNuDmst-pD0bar-kp_13TeV-pythia8_SoftQCD_PTFilter5_0p0-evtgen_HQET2_central_PU35_10-2-3_v0/B02DstMu_candidates/out/job$(ProcId).out
error          = /afs/cern.ch/user/o/ocerri/cernbox/BPhysics/data/cmsMC_private/BPH_NoCuts_Tag-B0_MuNuDmst-pD0bar-kp_13TeV-pythia8_SoftQCD_PTFilter5_0p0-evtgen_HQET2_central_PU35_10-2-3_v0/B02DstMu_candidates/out/job$(ProcId).err
log            = /afs/cern.ch/user/o/ocerri/cernbox/BPhysics/data/cmsMC_private/BPH_NoCuts_Tag-B0_MuNuDmst-pD0bar-kp_13TeV-pythia8_SoftQCD_PTFilter5_0p0-evtgen_HQET2_central_PU35_10-2-3_v0/B02DstMu_candidates/out/job$(ProcId).log
+MaxRuntime    = 3600
+JobBatchName  = MCmuPUnoCuts
x509userproxy  = $ENV(X509_USER_PROXY)
on_exit_remove = (ExitBySignal == False) && (ExitCode == 0)
max_retries    = 3
requirements   = Machine =!= LastRemoteHost
queue 1
